package org.foden.enums;

public enum SubMenu {
    POSMANAGER("POS Manager"),
    POSCONFIGURATION("POS Configuration"),
    ADDNEWPRODUCT("Add New product"),
    ALLPRODUCTS("All Products"),
    INHOUSEPRODUCTS("In House Products"),
    DIGITALPRODUCTS("Digital Products"),
    SELLERPRODUCT("Seller Product"),
    BULKIMPORT("Bulk Import"),
    BULKEXPORT("Bulk Export"),
    CATEGORY("Category"),
    CATEGORYBASEDDISCOUNT("Category Based Discount"),
    BRAND("Brand"),
    ATTRIBUTE("Attribute"),
    COLORS("Colors"),
    SIZEGUIDE("Size Guide"),
    PRODUCTREVIEWS("Product Reviews"),
    ADDNEWAUCTIONPRODUCT("Add New auction product"),
    ALLAUCTIONPRODUCTS("All Auction Products"),
    INHOUSEAUCTIONPRODUCTS("Inhouse Auction Products"),
    SELLERAUCTIONPRODUCTS("Seller Auction Products"),
    AUCTIONPRODUCTSORDERS("Auction Products Orders"),
    ADDNEWWHOLESALEPRODUCT("Add new wholesale product"),
    ALLWHOLESALEPRODUCTS("All wholesale products"),
    INHOUSEWHOLESALEPRODUCTS("In House Wholesale Products"),
    SELLERWHOLESALEPRODUCTS("Seller Wholesale Products"),
    ALLORDERS("All Orders"),
    INHOUSEORDERS("Inhouse orders"),
    SELLERORDERS("Seller Orders"),
    PICKUPPOINTORDER("Pick-up Point Order"),
    ALLDELIVERYBOY("All Delivery Boy"),
    ADDDELIVERYBOY("Add Delivery Boy"),
    PAYMENTHISTORIES("Payment Histories"),
    COLLECTEDHISTORIES("Collected Histories"),
    CANCELREQUEST("Cancel Request"),
    CONFIGURATION("Configuration"),
    REFUNDREQUEST("Refund Requests"),
    APPROVEDREFUNDS("Approved Refunds"),
    REJECTEDREFUNDS("Rejected Refunds"),
    REFUNDCONFIGURATION("Refund Configuration"),
    CUSTOMERLIST("Customer list"),
    CLASSIFIEDPRODUCTS("Classified Products"),
    CLASSIFIEDPACKAGES("Classified Packages"),
    ALLSELLER("All Seller"),
    PAYOUTS("Payouts"),
    PAYOUTREQUESTS("Payout Requests"),
    SELLERCOMMISSION("Seller Commission"),
    SELLERPACKAGES("Seller Packages"),
    SELLERVERIFICATIONFORM("Seller Verification Form"),
    INHOUSEPRODUCTSALE("In House Product Sale"),
    SELLERPRODUCTSSALE("Seller Products Sale"),
    PRODUCTSSTOCK("Products Stock"),
    PRODUCTSWISHLIST("Products wishlist"),
    USERSEARCHES("User Searches"),
    COMMISSIONHISTORY("Commission History"),
    WALLETRECHARGEHISTORY("Wallet Recharge History"),
    ALLPOSTS("All Posts"),
    CATEGORIES("Categories"),
    FLASHDEALS("Flash deals"),
    DYNAMICPOPUP("Dynamic Pop-up"),
    CUSTOMALERT("Custom Alert"),
    NEWSLETTERS("Newsletters"),
    BULKSMS("Bulk SMS"),
    SUBSCRIBERS("Subscribers"),
    COUPON("Coupon"),
    TICKET("Ticket"),
    PRODUCTCONVERSATIONS("Product Conversations"),
    PRODUCTQUERIES("Product Queries"),
    AFFILIATEREGISTRATIONFORM("Affiliate Registration Form"),
    AFFILIATECONFIGURATIONS("Affiliate Configurations"),
    AFFILIATEUSERS("Affiliate Users"),
    REFERRALUSERS("Referral Users"),
    AFFILIATEWITHDRAWREQUESTS("Affiliate Withdraw Requests"),
    AFFILIATELOGS("Affiliate Logs"),
    MANUALPAYMENTMETHODS("Manual Payment Methods"),
    OFFLINEWALLETRECHARGE("Offline Wallet Recharge"),
    OFFLINECUSTOMERPACKAGEPAYMENTS("Offline Customer Package Payments"),
    OFFICESELLERPACKAGEPAYMENTS("Offline Seller Package Payments"),
    SETASIANPGCREDENTIALS("Set Asian PG Credentials"),
    CLUBPOINTCONFIGURATION("Club Point Configurations"),
    SETPRODUCTPOINT("Set Product Point"),
    USERPOINTS("User Points"),
    OTPCONFIGURATIONS("OTP Configurations"),
    SMSTEMPLATES("SMS Templates"),
    SETOTPCREDENTIALS("Set OTP Credentials"),
    AFRICANPGCONFIGURATIONS("African PG Configurations"),
    SETAFRICANPGCREDENTIALS("Set African PG Credentials"),
    SELECTHOMEPAGE("Select Homepage"),
    HOMEPAGESETTINGS("Homepage Settings"),
    AUTHENTICATIONLAYOUTSETTINGS("Authentication Layout & Settings"),
    HEADER("Header"),
    FOOTER("Footer"),
    PAGES("Pages"),
    APPEARANCE("Appearance"),
    FEATURESACTIVATION("Features activation"),
    LANGUAGES("Languages"),
    CURRENCY("Currency"),
    VATTAX("Vat & TAX"),
    PICKUPPOINT("Pickup point"),
    SMTPSETTINS("SMTP Settings"),
    PAYMENTMETHODS("Payment Methods"),
    ORDERCONFIGURATION("Order Configuration"),
    FILESYSTEMCACHECONFIGURATION("File System & Cache Configuration"),
    SOCIALMEDIALOGINS("Social media Logins"),
    FACEBOOK("Facebook"),
    GOOGLE("Google"),
    SHIPPING("Shipping"),
    ALLSTAFFS("All staffs"),
    STAFFPERMISSIONS("Staff permissions"),
    UPDATE("Update"),
    SERVERSTATUS("Server status"),
    IMPORTDEMODATA("Import Demo Data"),
    ;
    private final String description;

    SubMenu(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
